### POST Create Group
POST http://localhost:8080/groups/create
Content-Type: application/json
Authorization: Bearer {{ authToken }}

{
  "name": "Test Group"
}

### POST Join Group
POST http://localhost:8080/groups/join
Content-Type: application/json
Authorization: Bearer {{ authToken2 }}

{
  "groupID": 1
}

### GET Groups
GET http://localhost:8080/groups
Content-Type: application/json
Authorization: Bearer {{ authToken }}